### ISSUE TITLE
Closing Otter upsell shouldn't redirect users to another page

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1074]
### Description:

[As discussed on Slack.](https://vertistudio.slack.com/archives/C02JC68P404/p1658484220312939)

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

**Comment by HardeepAsrani** [comment]
@mghenciu It was fixed in the last release and I just tested on WPorg version and it works properly.

**Comment by mghenciu** [comment]
> @mghenciu It was fixed in the last release and I just tested on WPorg version and it works properly.

Was still happening this morning on demosites.io.
Here's an ss from the [Apparel demo](https://demosites.io/apparel-gb/wp-admin/). Maybe it's the old notification, and until it's not closed, it will have the old logic 🤷
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/52494172/182366985-9d5ef7cc-9c8a-4cea-b4ba-68c747c31f7d.png">

**Comment by mghenciu** [comment]
> Nope, that's not how it works. I tried on that website you posted in the screenshot and I dismissed on the Plugins page and it redirected me to the plugins page, not to anyplace else.



ok, I thought we agreed on Slack that it should just close itself and that's it.
I tried again now on the [Book Shop site](https://demosites.io/book-shop-gb/), and as seen in the video - there is a redirect:

https://user-images.githubusercontent.com/52494172/182378679-828a9f88-fbf7-4953-9a80-b5d7c8c061a6.mov


___
Ideally, I think it should work like any other dismissible message, for example the ones from Neve & TPC:

https://user-images.githubusercontent.com/52494172/182378840-7863f292-2312-4b2f-b034-98e944cda25c.mov

**Comment by HardeepAsrani** [comment]
Aha, I get what you mean. You want us to replace the loading change and use AJAX instead.
