### ISSUE TITLE
Posts block has broken style in frontend when Post type is Product

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/otter-blocks#736]
If i add a **Posts** block and select the **Post type** to be **Product**, the style is broken in frontend, without making any change to the block settings (in editor it looks fine)

https://vertis.d.pr/GphxVc

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel ^

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, can you test using #689?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested both with #689 and #737 and the issue still happens

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, thanks for the checking.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, I can not reproduce the error. Can you give me an instance or the Woo products used in CSV format so I can import them?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Here is the instance:
```
https://otterposts.tastewp.com/2022/02/25/posts-block-with-products/
Username: irinel  
Password: KVPRD-bqwIE
```

**Comment by Soare-Robert-Daniel** [comment]
After some debugging, I found an interesting thing. The Woo products had some weird html tag in their description/excerpt.

A product data looks like this:

```
62,simple,,"White Blouse",1,0,visible,"<div class=""woocommerce-product-details__short-description"">\n\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.\n\n</div>","<div class=""woocommerce-product-details__short-description"">\n\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.\n\n</div>",,,taxable,,1,,,0,0,,,,,1,,,45,"Hat > Blouse",,,"https://otterposts.tastewp.com/wp-content/uploads/2019/03/tamara-bellis-XGhtJXY-yY-unsplash-1.jpg, https://otterposts.tastewp.com/wp-content/uploads/2019/03/tamara-bellis-9p8UKueTork-unsplash.jpg, https://otterposts.tastewp.com/wp-content/uploads/2019/03/ayo-ogunseinde-6W4F62sN_yI-unsplash-1.jpg, https://otterposts.tastewp.com/wp-content/uploads/2019/03/fezbot2000-nahUo1GhcrA-unsplash.jpg",,,,,,,,,0,,,,,18,70,60,,
```

![image](https://user-images.githubusercontent.com/17597852/155712671-3d2251a2-c98b-4bdc-87ff-16618abc907d.png)

@irinelenache, do you have the products from one of `demosites.io`?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel This is the demo https://demosites.io/shop-gb/

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, thanks for the source. A fix has been pushed to both PRs related to Posts. It should run correctly for now.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again with the specified PR's and the issue is still present
